name: AIS testing

on:
  push:
    branches:
      - main
      - dependencies
      - changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install OpenSSL dependencies
        run: sudo apt-get install libssl-dev
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Update cargo
        run: cargo update
      
      - name: Create users and group
        run: |
          sudo addgroup --system dusa
          sudo adduser --system dusa
      
      - name: Update submodule and run makefile
        run: |
          git submodule update --init --recursive
          cd dusa
          sudo make -f makefile
      